#!/bin/bash

set -ex

python setup.py develop

jupyter labextension install jupyterlab-plotly@4.14.1 --minimize=False
jupyter labextension install @jupyter-widgets/jupyterlab-manager plotlywidget@4.14.1 --minimize=False
